import { 
  InventoryItem, 
  ReliefRequest, 
  DeliveryRecord, 
  ShortageHeatmapDistrict 
} from '../types/relief';

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    item_id: 'INV-AS-01',
    item_name: 'Packaged Drinking Water (20L Cans)',
    category: 'Drinking Water',
    quantity: 6500,
    unit: 'liters',
    location: 'Guwahati State Disaster Warehouse',
    state: 'Assam',
    source: 'Government Warehouse',
    expiry_date: '2027-01-01',
    latitude: 26.1445,
    longitude: 91.7362,
    contact_person: 'Rajiv Baruah (ASDMA)',
    contact_phone: '+91 94350 11223'
  },
  {
    item_id: 'INV-AS-02',
    item_name: 'Emergency Food Packets (Rice, Dal, Biscuits)',
    category: 'Food',
    quantity: 12500,
    unit: 'packets',
    location: 'Silchar Flood Relief Staging Hub',
    state: 'Assam',
    source: 'Relief Centre',
    expiry_date: '2026-12-31',
    latitude: 24.8333,
    longitude: 92.7789,
    contact_person: 'Manas Paul (Red Cross Silchar)',
    contact_phone: '+91 94351 99887'
  },
  {
    item_id: 'INV-AS-03',
    item_name: 'Trauma & Water-borne Disease Medical Kits',
    category: 'Medicines',
    quantity: 850,
    unit: 'kits',
    location: 'Dibrugarh Medical College Depot',
    state: 'Assam',
    source: 'Government Warehouse',
    expiry_date: '2027-06-30',
    latitude: 27.4728,
    longitude: 94.9120,
    contact_person: 'Dr. Ananya Sarma',
    contact_phone: '+91 98640 55443'
  },
  {
    item_id: 'INV-ME-01',
    item_name: 'Thermal Blankets & Tarpaulins',
    category: 'Blankets & Clothes',
    quantity: 4200,
    unit: 'pieces',
    location: 'Shillong Civil Defence Reserve',
    state: 'Meghalaya',
    source: 'Government Warehouse',
    expiry_date: '2029-01-01',
    latitude: 25.5788,
    longitude: 91.8933,
    contact_person: 'P. Lyngdoh (SDMA)',
    contact_phone: '+91 98560 33211'
  },
  {
    item_id: 'INV-MN-01',
    item_name: 'Infant Nutrition & Baby Food Jars',
    category: 'Food',
    quantity: 1800,
    unit: 'packets',
    location: 'Imphal Community Aid Center',
    state: 'Manipur',
    source: 'NGO',
    expiry_date: '2026-11-15',
    latitude: 24.8170,
    longitude: 93.9368,
    contact_person: 'Thoiba Singh (NER Youth Action)',
    contact_phone: '+91 94360 44889'
  },
  {
    item_id: 'INV-SK-01',
    item_name: 'Emergency LED Torches & High-Capacity Batteries',
    category: 'Emergency Equipment',
    quantity: 950,
    unit: 'sets',
    location: 'Gangtok Mountain Rescue Base',
    state: 'Sikkim',
    source: 'Volunteer',
    latitude: 27.3389,
    longitude: 88.6065,
    contact_person: 'Tenzing Lepcha',
    contact_phone: '+91 97330 11990'
  },
  {
    item_id: 'INV-TR-01',
    item_name: 'Sanitary & Women Hygiene Care Packs',
    category: 'Sanitary & Hygiene',
    quantity: 3100,
    unit: 'packs',
    location: 'Agartala Municipal Supply Depot',
    state: 'Tripura',
    source: 'Government Warehouse',
    latitude: 23.8315,
    longitude: 91.2868,
    contact_person: 'Debashis Roy',
    contact_phone: '+91 94361 77665'
  },
  {
    item_id: 'INV-NL-01',
    item_name: 'Chlorine Tablets & Portable Water Filters',
    category: 'Drinking Water',
    quantity: 5000,
    unit: 'bottles',
    location: 'Dimapur Rotary Hub',
    state: 'Nagaland',
    source: 'Donor',
    latitude: 25.9090,
    longitude: 93.7266,
    contact_person: 'Keviletuo Angami',
    contact_phone: '+91 98620 44556'
  }
];

export const INITIAL_REQUESTS: ReliefRequest[] = [
  {
    request_id: 'REQ-NER-101',
    location: 'Borkhola Village, Cachar',
    state: 'Assam',
    district: 'Cachar',
    latitude: 24.8912,
    longitude: 92.7915,
    people_count: 320,
    required_item: 'Drinking Water',
    category: 'Drinking Water',
    quantity: 2500,
    unit: 'liters',
    urgency: 'CRITICAL',
    vulnerable: { children: 65, elderly: 42, pregnant: 8, injured: 14 },
    road_blocked: true,
    status: 'Verified',
    priority_score: 92.4,
    priority_class: 'CRITICAL',
    created_at: '2026-09-12 18:30',
    notes: 'Barak river breached embankment; village surrounded by flood water. Wells submerged.'
  },
  {
    request_id: 'REQ-NER-102',
    location: 'Sohra Hill Hamlet Sector 4',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    latitude: 25.2986,
    longitude: 91.7324,
    people_count: 140,
    required_item: 'Thermal Blankets & Tarpaulins',
    category: 'Blankets & Clothes',
    quantity: 300,
    unit: 'pieces',
    urgency: 'HIGH',
    vulnerable: { children: 28, elderly: 22, pregnant: 3, injured: 2 },
    road_blocked: true,
    status: 'Assigned',
    priority_score: 76.8,
    priority_class: 'HIGH',
    created_at: '2026-09-12 19:15',
    notes: 'Severe cloudburst caused slope slide damaging roofs; temperature dropping fast.'
  },
  {
    request_id: 'REQ-NER-103',
    location: 'Mangan North Transit Camp',
    state: 'Sikkim',
    district: 'Mangan',
    latitude: 27.5111,
    longitude: 88.5283,
    people_count: 85,
    required_item: 'Trauma & Water-borne Disease Medical Kits',
    category: 'Medicines',
    quantity: 50,
    unit: 'kits',
    urgency: 'CRITICAL',
    vulnerable: { children: 12, elderly: 9, pregnant: 2, injured: 11 },
    road_blocked: true,
    status: 'In Transit',
    priority_score: 88.5,
    priority_class: 'CRITICAL',
    created_at: '2026-09-12 17:45',
    notes: 'NH10 washed out; 11 people have crush injuries from rockfall. Helipad staging active.'
  },
  {
    request_id: 'REQ-NER-104',
    location: 'Kailashahar Ward 3',
    state: 'Tripura',
    district: 'Unakoti',
    latitude: 24.3756,
    longitude: 92.0048,
    people_count: 450,
    required_item: 'Emergency Food Packets',
    category: 'Food',
    quantity: 1350,
    unit: 'packets',
    urgency: 'HIGH',
    vulnerable: { children: 80, elderly: 50, pregnant: 7, injured: 3 },
    road_blocked: false,
    status: 'Requested',
    priority_score: 69.2,
    priority_class: 'HIGH',
    created_at: '2026-09-12 20:10',
    notes: 'Manu river overflow inundation. School shelter operational, food stock at 15%.'
  }
];

export const INITIAL_DELIVERIES: DeliveryRecord[] = [
  {
    distribution_id: 'DISP-NER-701',
    request_id: 'REQ-NER-103',
    source_depot: 'Gangtok Mountain Rescue Base',
    destination_camp: 'Mangan North Transit Camp',
    item: 'Medical Kits & First Aid Supplies',
    quantity: 50,
    unit: 'kits',
    transporter: 'Indian Air Force / SDRF Air Wing',
    vehicle_no: 'MI-17 Helo V-84',
    dispatch_time: '2026-09-12 20:00',
    estimated_arrival: '2026-09-12 21:30',
    delivery_status: 'In Transit',
    recipient_confirmed: false,
    transit_progress_pct: 65
  },
  {
    distribution_id: 'DISP-NER-702',
    request_id: 'REQ-NER-102',
    source_depot: 'Shillong Civil Defence Reserve',
    destination_camp: 'Sohra Hill Hamlet Sector 4',
    item: 'Thermal Blankets & Tarpaulins',
    quantity: 300,
    unit: 'pieces',
    transporter: 'Meghalaya Police 4x4 Quick Response',
    vehicle_no: 'ML-05-AB-4112',
    dispatch_time: '2026-09-12 19:40',
    estimated_arrival: '2026-09-12 22:00',
    delivery_status: 'Assigned',
    recipient_confirmed: false,
    transit_progress_pct: 25
  },
  {
    distribution_id: 'DISP-NER-700',
    request_id: 'REQ-NER-099',
    source_depot: 'Silchar Flood Relief Staging Hub',
    destination_camp: 'Hailakandi Central Relief Camp',
    item: 'Emergency Food Packets',
    quantity: 2000,
    unit: 'packets',
    transporter: 'NDRF 1st Battalion Motorboat Convoy',
    vehicle_no: 'NDRF-BOAT-09',
    dispatch_time: '2026-09-12 14:00',
    estimated_arrival: '2026-09-12 16:30',
    delivery_status: 'Delivered',
    recipient_confirmed: true,
    transit_progress_pct: 100
  }
];

export const INITIAL_HEATMAP_DISTRICTS: ShortageHeatmapDistrict[] = [
  {
    id: 'D-AS-01',
    district: 'Cachar (Silchar)',
    state: 'Assam',
    disaster_risk: 'CRITICAL',
    food_status: 'LOW',
    medical_status: 'CRITICAL',
    water_status: 'CRITICAL',
    overall_shortage: 'RED',
    active_shortage_count: 3500,
    latitude: 24.8333,
    longitude: 92.7789
  },
  {
    id: 'D-ME-01',
    district: 'East Khasi Hills (Shillong)',
    state: 'Meghalaya',
    disaster_risk: 'HIGH',
    food_status: 'ADEQUATE',
    medical_status: 'LOW',
    water_status: 'ADEQUATE',
    overall_shortage: 'ORANGE',
    active_shortage_count: 1100,
    latitude: 25.5788,
    longitude: 91.8933
  },
  {
    id: 'D-SK-01',
    district: 'Mangan',
    state: 'Sikkim',
    disaster_risk: 'CRITICAL',
    food_status: 'LOW',
    medical_status: 'CRITICAL',
    water_status: 'ADEQUATE',
    overall_shortage: 'RED',
    active_shortage_count: 890,
    latitude: 27.5111,
    longitude: 88.5283
  },
  {
    id: 'D-MN-01',
    district: 'Imphal West',
    state: 'Manipur',
    disaster_risk: 'MODERATE',
    food_status: 'ADEQUATE',
    medical_status: 'ADEQUATE',
    water_status: 'LOW',
    overall_shortage: 'YELLOW',
    active_shortage_count: 450,
    latitude: 24.8170,
    longitude: 93.9368
  },
  {
    id: 'D-AS-02',
    district: 'Kamrup Metropolitan (Guwahati)',
    state: 'Assam',
    disaster_risk: 'LOW',
    food_status: 'ADEQUATE',
    medical_status: 'ADEQUATE',
    water_status: 'ADEQUATE',
    overall_shortage: 'GREEN',
    active_shortage_count: 0,
    latitude: 26.1445,
    longitude: 91.7362
  },
  {
    id: 'D-TR-01',
    district: 'Unakoti (Kailashahar)',
    state: 'Tripura',
    disaster_risk: 'HIGH',
    food_status: 'LOW',
    medical_status: 'ADEQUATE',
    water_status: 'LOW',
    overall_shortage: 'ORANGE',
    active_shortage_count: 1400,
    latitude: 24.3756,
    longitude: 92.0048
  },
  {
    id: 'D-NL-01',
    district: 'Dimapur',
    state: 'Nagaland',
    disaster_risk: 'MODERATE',
    food_status: 'ADEQUATE',
    medical_status: 'ADEQUATE',
    water_status: 'ADEQUATE',
    overall_shortage: 'GREEN',
    active_shortage_count: 120,
    latitude: 25.9090,
    longitude: 93.7266
  },
  {
    id: 'D-MZ-01',
    district: 'Aizawl',
    state: 'Mizoram',
    disaster_risk: 'HIGH',
    food_status: 'ADEQUATE',
    medical_status: 'LOW',
    water_status: 'ADEQUATE',
    overall_shortage: 'YELLOW',
    active_shortage_count: 320,
    latitude: 23.7271,
    longitude: 92.7176
  }
];
